// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgdegvpfnilzkqpexgij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnZGVndnBmbmlsemtxcGV4Z2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjY3NjUsImV4cCI6MjA3MjQwMjc2NX0.k7Amb25bAU99bdgIAp6VlfBexLQ94HJYjjzV07f8QGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});